// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace TestProject1
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Admin Navigation and Login functionality")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class AdminNavigationAndLoginFunctionalityFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "", "Admin Navigation and Login functionality", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Login.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 5
 #line hidden
#line 7
 await testRunner.GivenAsync("the user is on the homepage", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
 await testRunner.WhenAsync("Enter the valid Dutum Advancedbutton and click proceed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
 await testRunner.ThenAsync("the page should be navigated to Dutum Main page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Login.feature.ndjson", 20);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify navigation to admin page")]
        [global::NUnit.Framework.CategoryAttribute("TC_LOGIN_001")]
        [global::NUnit.Framework.CategoryAttribute("Module_Admin")]
        [global::NUnit.Framework.CategoryAttribute("Priority_Low")]
        public async global::System.Threading.Tasks.Task VerifyNavigationToAdminPage()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_LOGIN_001",
                    "Module_Admin",
                    "Priority_Low"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify navigation to admin page", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await this.FeatureBackgroundAsync();
#line hidden
#line 13
 await testRunner.WhenAsync("Click on the Admin button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify Successful Admin login and navigating to Dashboard")]
        [global::NUnit.Framework.CategoryAttribute("TC_LOGIN_002")]
        [global::NUnit.Framework.CategoryAttribute("Module_Login")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        public async global::System.Threading.Tasks.Task VerifySuccessfulAdminLoginAndNavigatingToDashboard()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_LOGIN_002",
                    "Module_Login",
                    "Priority_High"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify Successful Admin login and navigating to Dashboard", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 16
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await this.FeatureBackgroundAsync();
#line hidden
#line 17
 await testRunner.WhenAsync("Click on the Admin button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
 await testRunner.WhenAsync("Enter the valid main username and password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
 await testRunner.ThenAsync("the page should be navigated to the dashboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify logged-in username is displayed")]
        [global::NUnit.Framework.CategoryAttribute("TC_LOGIN_003")]
        [global::NUnit.Framework.CategoryAttribute("Module_Login")]
        [global::NUnit.Framework.CategoryAttribute("Priority_Low")]
        public async global::System.Threading.Tasks.Task VerifyLogged_InUsernameIsDisplayed()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_LOGIN_003",
                    "Module_Login",
                    "Priority_Low"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify logged-in username is displayed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 22
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await this.FeatureBackgroundAsync();
#line hidden
#line 24
 await testRunner.WhenAsync("Click on the Admin button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
 await testRunner.WhenAsync("Enter the valid main username and password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
 await testRunner.ThenAsync("The username should be displayed on the top right corner", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify Dashboard Url after successful login")]
        [global::NUnit.Framework.CategoryAttribute("TC_LOGIN_004")]
        [global::NUnit.Framework.CategoryAttribute("Module_Login")]
        [global::NUnit.Framework.CategoryAttribute("Priority_Low")]
        public async global::System.Threading.Tasks.Task VerifyDashboardUrlAfterSuccessfulLogin()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_LOGIN_004",
                    "Module_Login",
                    "Priority_Low"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify Dashboard Url after successful login", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await this.FeatureBackgroundAsync();
#line hidden
#line 32
 await testRunner.WhenAsync("Click on the Admin button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
 await testRunner.WhenAsync("Enter the valid main username and password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
 await testRunner.ThenAsync("the user should redirected to the dashboard page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Validate session creation after successful login")]
        [global::NUnit.Framework.CategoryAttribute("TC_LOGIN_005")]
        [global::NUnit.Framework.CategoryAttribute("Module_Login")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        public async global::System.Threading.Tasks.Task ValidateSessionCreationAfterSuccessfulLogin()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_LOGIN_005",
                    "Module_Login",
                    "Priority_High"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validate session creation after successful login", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await this.FeatureBackgroundAsync();
#line hidden
#line 39
 await testRunner.WhenAsync("Click on the Admin button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 40
 await testRunner.WhenAsync("Enter the valid main username and password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
 await testRunner.ThenAsync("the user should redirected to the dashboard page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 42
 await testRunner.AndAsync("Logout button should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Invalid login with multiple Usernames and Passwords")]
        [global::NUnit.Framework.CategoryAttribute("TC_LOGIN_006")]
        [global::NUnit.Framework.CategoryAttribute("Module_invalidlogin")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        [global::NUnit.Framework.TestCaseAttribute("user1", "pass1", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("user2", "pass2", "6", null)]
        public async global::System.Threading.Tasks.Task InvalidLoginWithMultipleUsernamesAndPasswords(string username, string password, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TC_LOGIN_006",
                    "Module_invalidlogin",
                    "Priority_High"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("username", username);
            argumentsOfScenario.Add("password", password);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Invalid login with multiple Usernames and Passwords", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 45
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await this.FeatureBackgroundAsync();
#line hidden
#line 47
 await testRunner.WhenAsync("Click on the Admin button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 48
 await testRunner.WhenAsync(string.Format("Enter the invalid username \"{0}\" and password \"{1}\"", username, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
 await testRunner.ThenAsync("the error message should be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("User clicks Dutum Login button with empty fields")]
        [global::NUnit.Framework.CategoryAttribute("TC_LOGIN_007")]
        [global::NUnit.Framework.CategoryAttribute("Module_invalidlogin")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        public async global::System.Threading.Tasks.Task UserClicksDutumLoginButtonWithEmptyFields()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_LOGIN_007",
                    "Module_invalidlogin",
                    "Priority_High"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("User clicks Dutum Login button with empty fields", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 58
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await this.FeatureBackgroundAsync();
#line hidden
#line 59
 await testRunner.WhenAsync("Click on the Admin button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 60
 await testRunner.WhenAsync("Enter the invalid username \"\" and password \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
 await testRunner.ThenAsync("the error message should be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("User clicks Dutum Login button with empty username")]
        [global::NUnit.Framework.CategoryAttribute("TC_LOGIN_008")]
        [global::NUnit.Framework.CategoryAttribute("Module_invalidlogin")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        public async global::System.Threading.Tasks.Task UserClicksDutumLoginButtonWithEmptyUsername()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_LOGIN_008",
                    "Module_invalidlogin",
                    "Priority_High"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("User clicks Dutum Login button with empty username", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 65
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await this.FeatureBackgroundAsync();
#line hidden
#line 67
 await testRunner.WhenAsync("Click on the Admin button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 68
 await testRunner.WhenAsync("Enter the invalid username \"\" and password \"pass123\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
 await testRunner.ThenAsync("the error message should be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("User clicks Dutum Login button with empty password")]
        [global::NUnit.Framework.CategoryAttribute("TC_LOGIN_009")]
        [global::NUnit.Framework.CategoryAttribute("Module_invalidlogin")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        public async global::System.Threading.Tasks.Task UserClicksDutumLoginButtonWithEmptyPassword()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_LOGIN_009",
                    "Module_invalidlogin",
                    "Priority_High"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("User clicks Dutum Login button with empty password", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 72
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await this.FeatureBackgroundAsync();
#line hidden
#line 74
 await testRunner.WhenAsync("Click on the Admin button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 75
 await testRunner.WhenAsync("Enter the invalid username \"user123\" and password \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 76
 await testRunner.ThenAsync("the error message should be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("User clicks Dutum Login button with special characters")]
        [global::NUnit.Framework.CategoryAttribute("TC_LOGIN_010")]
        [global::NUnit.Framework.CategoryAttribute("Module_invalidlogin")]
        [global::NUnit.Framework.CategoryAttribute("Priority_Medium")]
        public async global::System.Threading.Tasks.Task UserClicksDutumLoginButtonWithSpecialCharacters()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_LOGIN_010",
                    "Module_invalidlogin",
                    "Priority_Medium"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("User clicks Dutum Login button with special characters", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 79
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await this.FeatureBackgroundAsync();
#line hidden
#line 81
 await testRunner.WhenAsync("Click on the Admin button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 82
 await testRunner.WhenAsync("Enter the invalid username \"user!@#\" and password \"pass!@#\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 83
 await testRunner.ThenAsync("the error message should be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("User clicks Dutum Login button with SQL injection")]
        [global::NUnit.Framework.CategoryAttribute("TC_LOGIN_011")]
        [global::NUnit.Framework.CategoryAttribute("Module_invalidlogin")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        public async global::System.Threading.Tasks.Task UserClicksDutumLoginButtonWithSQLInjection()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_LOGIN_011",
                    "Module_invalidlogin",
                    "Priority_High"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("User clicks Dutum Login button with SQL injection", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 86
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await this.FeatureBackgroundAsync();
#line hidden
#line 88
 await testRunner.WhenAsync("Click on the Admin button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 89
 await testRunner.WhenAsync("Enter the invalid username \"admin\' OR \'1\'=\'1\" and password \"password\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 90
 await testRunner.ThenAsync("the error message should be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Successful logout after login")]
        [global::NUnit.Framework.CategoryAttribute("TC_LOGIN_012")]
        [global::NUnit.Framework.CategoryAttribute("Module_logout")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        public async global::System.Threading.Tasks.Task SuccessfulLogoutAfterLogin()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_LOGIN_012",
                    "Module_logout",
                    "Priority_High"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successful logout after login", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 93
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await this.FeatureBackgroundAsync();
#line hidden
#line 95
 await testRunner.WhenAsync("Click on the Admin button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 96
 await testRunner.WhenAsync("Enter the valid main username and password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 97
 await testRunner.ThenAsync("the user should redirected to the dashboard page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 98
 await testRunner.WhenAsync("click the user image button on the top right corner", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 99
 await testRunner.ThenAsync("In dropdown click on logout button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 100
 await testRunner.ThenAsync("the user should be redirected to the home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Back button functionality after logout")]
        [global::NUnit.Framework.CategoryAttribute("TC_LOGIN_013")]
        [global::NUnit.Framework.CategoryAttribute("Module_logout")]
        [global::NUnit.Framework.CategoryAttribute("Priority_Medium")]
        public async global::System.Threading.Tasks.Task BackButtonFunctionalityAfterLogout()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_LOGIN_013",
                    "Module_logout",
                    "Priority_Medium"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Back button functionality after logout", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 103
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await this.FeatureBackgroundAsync();
#line hidden
#line 104
 await testRunner.WhenAsync("Click on the Admin button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 105
 await testRunner.WhenAsync("Enter the valid main username and password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 106
 await testRunner.ThenAsync("the user should redirected to the dashboard page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 107
 await testRunner.WhenAsync("click the user image button on the top right corner", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 108
 await testRunner.ThenAsync("In dropdown click on logout button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 109
 await testRunner.ThenAsync("the user should be redirected to the home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify Attendance page opens when Attendance menu is clicked")]
        [global::NUnit.Framework.CategoryAttribute("TC_LOGIN_014")]
        [global::NUnit.Framework.CategoryAttribute("Module_Attendance")]
        [global::NUnit.Framework.CategoryAttribute("Priority_Medium")]
        public async global::System.Threading.Tasks.Task VerifyAttendancePageOpensWhenAttendanceMenuIsClicked()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_LOGIN_014",
                    "Module_Attendance",
                    "Priority_Medium"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify Attendance page opens when Attendance menu is clicked", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 112
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await this.FeatureBackgroundAsync();
#line hidden
#line 114
 await testRunner.WhenAsync("Click on the Admin button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 115
 await testRunner.WhenAsync("Enter the valid main username and password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 116
 await testRunner.ThenAsync("the user should redirected to the dashboard page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 117
 await testRunner.WhenAsync("Click on the Attendance menu", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 118
 await testRunner.ThenAsync("the attendance page will be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify Timesheet page opens when Timesheet menu is clicked")]
        [global::NUnit.Framework.CategoryAttribute("TC_LOGIN_015")]
        [global::NUnit.Framework.CategoryAttribute("Module_Timesheet")]
        [global::NUnit.Framework.CategoryAttribute("Priority_Medium")]
        public async global::System.Threading.Tasks.Task VerifyTimesheetPageOpensWhenTimesheetMenuIsClicked()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_LOGIN_015",
                    "Module_Timesheet",
                    "Priority_Medium"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify Timesheet page opens when Timesheet menu is clicked", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 121
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await this.FeatureBackgroundAsync();
#line hidden
#line 123
 await testRunner.WhenAsync("Click on the Admin button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 124
 await testRunner.WhenAsync("Enter the valid main username and password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 125
 await testRunner.ThenAsync("the user should redirected to the dashboard page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 126
 await testRunner.WhenAsync("Click on the Timesheet menu", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 127
 await testRunner.ThenAsync("the timesheet page will be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify Resource page opens when Resource menu is clicked")]
        [global::NUnit.Framework.CategoryAttribute("TC_LOGIN_016")]
        [global::NUnit.Framework.CategoryAttribute("Module_Resource")]
        [global::NUnit.Framework.CategoryAttribute("Priority_Medium")]
        public async global::System.Threading.Tasks.Task VerifyResourcePageOpensWhenResourceMenuIsClicked()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_LOGIN_016",
                    "Module_Resource",
                    "Priority_Medium"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify Resource page opens when Resource menu is clicked", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 130
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await this.FeatureBackgroundAsync();
#line hidden
#line 131
 await testRunner.WhenAsync("Click on the Admin button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 132
 await testRunner.WhenAsync("Enter the valid main username and password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 133
 await testRunner.ThenAsync("the user should redirected to the dashboard page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 134
 await testRunner.WhenAsync("Click on the Resource menu", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 135
 await testRunner.ThenAsync("the resource page will be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify Organisation page opens when Organisation menu is clicked")]
        [global::NUnit.Framework.CategoryAttribute("TC_LOGIN_017")]
        [global::NUnit.Framework.CategoryAttribute("Module_Organisation")]
        [global::NUnit.Framework.CategoryAttribute("Priority_Medium")]
        public async global::System.Threading.Tasks.Task VerifyOrganisationPageOpensWhenOrganisationMenuIsClicked()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_LOGIN_017",
                    "Module_Organisation",
                    "Priority_Medium"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify Organisation page opens when Organisation menu is clicked", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 138
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await this.FeatureBackgroundAsync();
#line hidden
#line 139
 await testRunner.WhenAsync("Click on the Admin button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 140
 await testRunner.WhenAsync("Enter the valid main username and password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 141
 await testRunner.ThenAsync("the user should redirected to the dashboard page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 142
 await testRunner.WhenAsync("Click on the Organisation menu", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 143
 await testRunner.ThenAsync("the organisation page will be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
