// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace TestProject1.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("User Management")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class UserManagementFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "User Management", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "UserManagement.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 3
#line hidden
#line 5
 await testRunner.GivenAsync("the user is on the homepage", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
 await testRunner.WhenAsync("Enter the valid Dutum Advancedbutton and click proceed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 7
 await testRunner.ThenAsync("the page should be navigated to Dutum Main page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 8
 await testRunner.WhenAsync("Click on the Admin button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
 await testRunner.WhenAsync("Enter the valid main username and password", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
 await testRunner.ThenAsync("the user should redirected to the dashboard page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 11
 await testRunner.WhenAsync("Click on the user list button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/UserManagement.feature.ndjson", 16);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Navigate to User Management page")]
        [global::NUnit.Framework.CategoryAttribute("TC_User_EMP_001")]
        [global::NUnit.Framework.CategoryAttribute("Module_User")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        public async global::System.Threading.Tasks.Task NavigateToUserManagementPage()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_User_EMP_001",
                    "Module_User",
                    "Priority_High"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Navigate to User Management page", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 16
 await testRunner.ThenAsync("click user list page will be display on the screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify Add_User button functionality")]
        [global::NUnit.Framework.CategoryAttribute("TC_User_EMP_002")]
        [global::NUnit.Framework.CategoryAttribute("Module_User")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        public async global::System.Threading.Tasks.Task VerifyAdd_UserButtonFunctionality()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_User_EMP_002",
                    "Module_User",
                    "Priority_High"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify Add_User button functionality", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 20
 await testRunner.WhenAsync("click on the Add_User button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
 await testRunner.ThenAsync("add user page will be display on screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify Search by Employee name functionality with first letter as capital")]
        [global::NUnit.Framework.CategoryAttribute("TC_User_EMP_003")]
        [global::NUnit.Framework.CategoryAttribute("Module_User")]
        [global::NUnit.Framework.CategoryAttribute("Priority_Medium")]
        public async global::System.Threading.Tasks.Task VerifySearchByEmployeeNameFunctionalityWithFirstLetterAsCapital()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_User_EMP_003",
                    "Module_User",
                    "Priority_Medium"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify Search by Employee name functionality with first letter as capital", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 26
 await testRunner.WhenAsync("enter the Employee name in search field in first letter as capital", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
 await testRunner.ThenAsync("the searched Name with first letter as capital will be displayed in the user list" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify Search by Employee name functionality with first letter as small")]
        [global::NUnit.Framework.CategoryAttribute("TC_User_EMP_004")]
        [global::NUnit.Framework.CategoryAttribute("Module_User")]
        [global::NUnit.Framework.CategoryAttribute("Priority_Medium")]
        public async global::System.Threading.Tasks.Task VerifySearchByEmployeeNameFunctionalityWithFirstLetterAsSmall()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_User_EMP_004",
                    "Module_User",
                    "Priority_Medium"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify Search by Employee name functionality with first letter as small", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 32
 await testRunner.WhenAsync("enter the Employee name in search field in first letter as small", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
 await testRunner.ThenAsync("the searched Name with first letter as small will be displayed in the user list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify Search by user Email functionality")]
        [global::NUnit.Framework.CategoryAttribute("TC_User_EMP_005")]
        [global::NUnit.Framework.CategoryAttribute("Module_User")]
        [global::NUnit.Framework.CategoryAttribute("Priority_Medium")]
        public async global::System.Threading.Tasks.Task VerifySearchByUserEmailFunctionality()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_User_EMP_005",
                    "Module_User",
                    "Priority_Medium"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify Search by user Email functionality", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 38
 await testRunner.WhenAsync("enter the user Email in search field", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
 await testRunner.ThenAsync("the entered user Email will be displayed in the user list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify Search by user Mobile_Num functionality")]
        [global::NUnit.Framework.CategoryAttribute("TC_User_EMP_006")]
        [global::NUnit.Framework.CategoryAttribute("Module_User")]
        [global::NUnit.Framework.CategoryAttribute("Priority_Medium")]
        public async global::System.Threading.Tasks.Task VerifySearchByUserMobile_NumFunctionality()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_User_EMP_006",
                    "Module_User",
                    "Priority_Medium"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify Search by user Mobile_Num functionality", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 42
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 44
 await testRunner.WhenAsync("enter the user Mobile_Num in search field", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
 await testRunner.ThenAsync("the entered user Mobile_Num will be displayed in the user list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify Search by user role functionality")]
        [global::NUnit.Framework.CategoryAttribute("TC_User_EMP_007")]
        [global::NUnit.Framework.CategoryAttribute("Module_User")]
        [global::NUnit.Framework.CategoryAttribute("Priority_Medium")]
        public async global::System.Threading.Tasks.Task VerifySearchByUserRoleFunctionality()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_User_EMP_007",
                    "Module_User",
                    "Priority_Medium"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify Search by user role functionality", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 49
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 51
 await testRunner.WhenAsync("select the user role in search field", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
 await testRunner.ThenAsync("the searched user role will be displayed in the user list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify the name field accept alphanumeric value")]
        [global::NUnit.Framework.CategoryAttribute("TC_User_EMP_008")]
        [global::NUnit.Framework.CategoryAttribute("Module_User")]
        [global::NUnit.Framework.CategoryAttribute("Priority_Low")]
        public async global::System.Threading.Tasks.Task VerifyTheNameFieldAcceptAlphanumericValue()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_User_EMP_008",
                    "Module_User",
                    "Priority_Low"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify the name field accept alphanumeric value", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 57
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 59
 await testRunner.ThenAsync("click user list page will be display on the screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 60
 await testRunner.WhenAsync("click on the Add_User button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
 await testRunner.ThenAsync("add user page will be display on screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 62
 await testRunner.WhenAsync("enter the mandatory fields and with name field accept alphanumeric value", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify the name field accept numerical value")]
        [global::NUnit.Framework.CategoryAttribute("TC_User_EMP_009")]
        [global::NUnit.Framework.CategoryAttribute("Module_User")]
        [global::NUnit.Framework.CategoryAttribute("Priority_Low")]
        public async global::System.Threading.Tasks.Task VerifyTheNameFieldAcceptNumericalValue()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_User_EMP_009",
                    "Module_User",
                    "Priority_Low"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify the name field accept numerical value", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 66
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 68
 await testRunner.ThenAsync("click user list page will be display on the screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 69
 await testRunner.WhenAsync("click on the Add_User button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 70
 await testRunner.ThenAsync("add user page will be display on screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 71
 await testRunner.WhenAsync("enter the mandatory fields and with name field accept numerical value", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Add user with mandatory fields")]
        [global::NUnit.Framework.CategoryAttribute("TC_User_EMP_010")]
        [global::NUnit.Framework.CategoryAttribute("Module_User")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        public async global::System.Threading.Tasks.Task AddUserWithMandatoryFields()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_User_EMP_010",
                    "Module_User",
                    "Priority_High"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Add user with mandatory fields", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 75
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 77
 await testRunner.ThenAsync("click user list page will be display on the screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 78
 await testRunner.WhenAsync("click on the Add_User button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
 await testRunner.ThenAsync("add user page will be display on screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Email",
                            "Mobile",
                            "Assign_Client",
                            "Gender",
                            "Assign_Skill",
                            "Account_Name",
                            "Account_Email",
                            "Designation",
                            "Joined_Date",
                            "Reporting_To",
                            "Role",
                            "Employee_Code",
                            "Salary",
                            "Account_Number",
                            "Account_Phone"});
                table1.AddRow(new string[] {
                            "Heera",
                            "heerayatha@gmail.com",
                            "9677185680",
                            "Aarding",
                            "Female",
                            "HiCAD Modeling (Machine Building)",
                            "Heera",
                            "moti4462@gmail.com",
                            "Junior Project Engineer",
                            "23",
                            "superadmin",
                            "IT Admin",
                            "EMP123",
                            "50000",
                            "1234567890",
                            "9876543210"});
#line 80
 await testRunner.WhenAsync("enter the mandatory fields", ((string)(null)), table1, "When ");
#line hidden
#line 83
 await testRunner.AndAsync("click on the save button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify employee details are saved successfully")]
        [global::NUnit.Framework.CategoryAttribute("TC_User_EMP_011")]
        [global::NUnit.Framework.CategoryAttribute("Module_User")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        public async global::System.Threading.Tasks.Task VerifyEmployeeDetailsAreSavedSuccessfully()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_User_EMP_011",
                    "Module_User",
                    "Priority_High"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify employee details are saved successfully", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 86
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 88
 await testRunner.ThenAsync("click user list page will be display on the screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 89
 await testRunner.WhenAsync("click on the Add_User button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 90
 await testRunner.ThenAsync("add user page will be display on screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Email",
                            "Mobile",
                            "Assign_Client",
                            "Gender",
                            "Assign_Skill",
                            "Account_Name",
                            "Account_Email",
                            "Designation",
                            "Joined_Date",
                            "Reporting_To",
                            "Role",
                            "Employee_Code",
                            "Salary",
                            "Account_Number",
                            "Account_Phone"});
                table2.AddRow(new string[] {
                            "Heera",
                            "heerayatha@gmail.com",
                            "9677185680",
                            "Aarding",
                            "Female",
                            "HiCAD Modeling (Machine Building)",
                            "Heera",
                            "moti4462@gmail.com",
                            "Junior Project Engineer",
                            "23",
                            "superadmin",
                            "IT Admin",
                            "EMP123",
                            "50000",
                            "1234567890",
                            "9876543210"});
#line 91
 await testRunner.WhenAsync("enter the mandatory fields", ((string)(null)), table2, "When ");
#line hidden
#line 94
 await testRunner.AndAsync("click on the save button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 95
 await testRunner.AndAsync("a success message should be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 96
 await testRunner.AndAsync("the employee should appear in the employee list", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify duplicate Employee ID is not allowed")]
        [global::NUnit.Framework.CategoryAttribute("TC_USER_EMP_012")]
        [global::NUnit.Framework.CategoryAttribute("Module_User")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        public async global::System.Threading.Tasks.Task VerifyDuplicateEmployeeIDIsNotAllowed()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_USER_EMP_012",
                    "Module_User",
                    "Priority_High"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify duplicate Employee ID is not allowed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 99
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 100
    await testRunner.ThenAsync("click user list page will be display on the screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 101
 await testRunner.WhenAsync("click on the Add_User button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 102
 await testRunner.ThenAsync("add user page will be display on screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Email",
                            "Mobile",
                            "Assign_Client",
                            "Gender",
                            "Assign_Skill",
                            "Account_Name",
                            "Account_Email",
                            "Designation",
                            "Joined_Date",
                            "Reporting_To",
                            "Role",
                            "Employee_Code",
                            "Salary",
                            "Account_Number",
                            "Account_Phone"});
                table3.AddRow(new string[] {
                            "Heera",
                            "heerayatha@gmail.com",
                            "9677185680",
                            "Aarding",
                            "Female",
                            "HiCAD Modeling (Machine Building)",
                            "Heera",
                            "moti4462@gmail.com",
                            "Junior Project Engineer",
                            "23",
                            "superadmin",
                            "IT Admin",
                            "EMP123",
                            "50000",
                            "1234567890",
                            "9876543210"});
#line 103
 await testRunner.WhenAsync("enter the mandatory fields with employee ID \"EMP123\"", ((string)(null)), table3, "When ");
#line hidden
#line 106
 await testRunner.AndAsync("click on the save button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 107
    await testRunner.ThenAsync("an \"Employee ID already exists\" error message should be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify duplicate Email is not allowed")]
        [global::NUnit.Framework.CategoryAttribute("TC_USER_EMP_013")]
        [global::NUnit.Framework.CategoryAttribute("Module_User")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        public async global::System.Threading.Tasks.Task VerifyDuplicateEmailIsNotAllowed()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_USER_EMP_013",
                    "Module_User",
                    "Priority_High"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify duplicate Email is not allowed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 111
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 112
    await testRunner.ThenAsync("click user list page will be display on the screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 113
 await testRunner.WhenAsync("click on the Add_User button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 114
 await testRunner.ThenAsync("add user page will be display on screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Email",
                            "Mobile",
                            "Assign_Client",
                            "Gender",
                            "Assign_Skill",
                            "Account_Name",
                            "Account_Email",
                            "Designation",
                            "Joined_Date",
                            "Reporting_To",
                            "Role",
                            "Employee_Code",
                            "Salary",
                            "Account_Number",
                            "Account_Phone"});
                table4.AddRow(new string[] {
                            "Heera",
                            "heerayatha@gmail.com",
                            "9677185680",
                            "Aarding",
                            "Female",
                            "HiCAD Modeling (Machine Building)",
                            "Heera",
                            "moti4462@gmail.com",
                            "Junior Project Engineer",
                            "23",
                            "superadmin",
                            "IT Admin",
                            "EMP123",
                            "50000",
                            "1234567890",
                            "9876543210"});
#line 115
 await testRunner.WhenAsync("enter the mandatory fields with email \"test@example.com\"", ((string)(null)), table4, "When ");
#line hidden
#line 118
 await testRunner.AndAsync("click on the save button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 119
    await testRunner.ThenAsync("an \"Email already exists\" error message should be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify duplicate Mobile Number is not allowed")]
        [global::NUnit.Framework.CategoryAttribute("TC_USER_EMP_014")]
        [global::NUnit.Framework.CategoryAttribute("Module_User")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        public async global::System.Threading.Tasks.Task VerifyDuplicateMobileNumberIsNotAllowed()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_USER_EMP_014",
                    "Module_User",
                    "Priority_High"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify duplicate Mobile Number is not allowed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 122
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
await this.FeatureBackgroundAsync();
#line hidden
#line 123
 await testRunner.ThenAsync("click user list page will be display on the screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 124
 await testRunner.WhenAsync("click on the Add_User button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 125
 await testRunner.ThenAsync("add user page will be display on screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Email",
                            "Mobile",
                            "Assign_Client",
                            "Gender",
                            "Assign_Skill",
                            "Account_Name",
                            "Account_Email",
                            "Designation",
                            "Joined_Date",
                            "Reporting_To",
                            "Role",
                            "Employee_Code",
                            "Salary",
                            "Account_Number",
                            "Account_Phone"});
                table5.AddRow(new string[] {
                            "Heera",
                            "heerayatha@gmail.com",
                            "9677185680",
                            "Aarding",
                            "Female",
                            "HiCAD Modeling (Machine Building)",
                            "Heera",
                            "moti4462@gmail.com",
                            "Junior Project Engineer",
                            "23",
                            "superadmin",
                            "IT Admin",
                            "EMP123",
                            "50000",
                            "1234567890",
                            "9876543210"});
#line 126
 await testRunner.WhenAsync("enter the mandatory fields with mobile number \"9677185680\"", ((string)(null)), table5, "When ");
#line hidden
#line 129
 await testRunner.AndAsync("click on the save button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 130
    await testRunner.ThenAsync("an \"Mobile number already exists\" error message should be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
